config/routes.rb
Liquidum::Engine.routes.draw do
  resources :completions
  resources :conversions
  resources :sandbox
  post 'render_only', to: 'sandbox#render_only'
end

app/models/concerns/liquidum/to_liquid.rb
# frozen_literal_strings: true

module Liquidum
  module ToLiquid
    extend ActiveSupport::Concern

    included do
      def to_liquid
        klass = "#{self.class.name}Drop".safe_constantize
        klass ||= "#{self.class.base_class.name}Drop".safe_constantize if self.class.respond_to?(:base_class)
        raise "No Drop defined for #{self.class.name}" unless klass

        klass.new(self)
      end
    end
  end
end

app/models/liquidum/sandbox.rb
module Liquidum
  class Sandbox < ApplicationRecord
    attribute :result, default: ''

    validates :context, presence: true
    validates :template, presence: true
  end
end

app/controllers/liquidum/application_controller.rb
module Liquidum
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/liquidum/completions_controller.rb
require_dependency "liquidum/application_controller"

module Liquidum
  class CompletionsController < ApplicationController
    def index
      q          = params[:q]
      klass      = q.classify.safe_constantize
      drop       = q.classify.concat('Drop').safe_constantize
      invokables = drop&.invokable_methods || []
      # drop_relations = klass.reflect_on_all_associations.map(&:name).select {|n| invokables.include?(n.to_s) }

      render json: { q: q, completions: invokables }
    end
  end
end

app/controllers/liquidum/conversions_controller.rb
module Liquidum
  class ConversionsController < ApplicationController
    before_action :set_objects
    class Conversion
      include ActiveModel::Model

      attr_accessor :source, :result
    end

    def index; end

    def create
      if params[:json_to_yaml] == 'commit'
        @conversion.result = YAML.dump(JSON.parse(@conversion.source))
      elsif params[:yaml_to_json] == 'commit'
        @conversion.result = JSON.pretty_generate(Psych.load(@conversion.source))
      elsif params[:slim_to_html] == 'commit'
        @conversion.result = Slim::Template.new({ pretty: true }) { @conversion.source }.render
      end

      render :index, status: 302
    end

    private

    def set_objects
      @conversion = Conversion.new(source: params.dig(:conversions_controller_conversion, :source) || '')
    end
  end
end

app/controllers/liquidum/sandbox_controller.rb
require_dependency "liquidum/application_controller"

module Liquidum
  class SandboxController < ApplicationController
    before_action :set_objects, except: %i[index]

    def index
    end

    def new
      render :edit
    end

    def create
      return render_only if params[:render_only] == "commit"

      @sandbox.update(sandbox_attributes)

      respond_with @sandbox,
        collection_location: -> { edit_sandbox_path(@sandbox) },
        action: :edit
    end

    def edit
      if @sandbox.valid?
        @sandbox.result = Liquidum.render(@sandbox.template, assigns: JSON.parse(@sandbox.context))
      end
    end

    def update
      return render_only if params[:render_only] == "commit"

      @sandbox.update(sandbox_attributes)

      respond_with @sandbox,
        collection_location: -> { edit_sandbox_path(@sandbox) },
        action: :edit
    end

    private

    def render_only
      @sandbox.assign_attributes(sandbox_attributes)

      if @sandbox.valid?
        @sandbox.result = Liquidum.render(@sandbox.template, assigns: JSON.parse(@sandbox.context))
      end
      render :edit, status: 302
    end

    def set_objects
      @sandbox = Sandbox.find(params[:id]) if params[:id]
      @sandbox ||= Sandbox.new(template: "{{test}}", context: '{"test": "context"}')
    end

    def sandbox_attributes
      params.require(:sandbox).permit(:context, :template, :description)
    end
  end
end

app/helpers/liquidum/application_helper.rb
module Liquidum
  module ApplicationHelper
    def liquidum_sandboxes_menu
      Satis::Menus::Builder.build(:admin_tickets) do |m|
        m.item :create, icon: 'fal fa-plus', link: new_sandbox_path
      end
    end
  end
end

app/views/liquidum/conversions/index.html.slim
= sts.form_for(@conversion, url: conversions_path, data: { turbo: false }) do |f|
  = sts.card(title: 'Conversions') do |card|
    - card.with_action
      = f.submit "JSON -> YAML", name: "json_to_yaml"
      = f.submit "YAML -> JSON", name: "yaml_to_json"
      = f.submit "SLIM -> HTML", name: "slim_to_html"
    - card.with_tab :main, padding: true
        .grid.grid-cols-12.gap-4
          .col-span-12
            = f.editor :source, mode: "application/json"
          .col-span-12
            = f.editor :result, mode: "text/plain", read_only: true

app/views/liquidum/sandbox/edit.html.slim
= sts.form_for(@sandbox, url: @sandbox.persisted? ? sandbox_path(@sandbox) : sandbox_index_path) do |f|
  = sts.card(title: 'Liquid Sandbox') do |card|
    - card.with_action
      = f.submit "Save", value: 'save'
    - card.with_action
      = f.submit t('.render'), name: "render_only"
    - card.with_tab :main, padding: true
      .grid.grid-cols-12.gap-4
        .col-span-12
          = f.input :description
        .col-span-12
          = f.editor :context, mode: "application/json"
        .col-span-12
          = f.editor :template, mode: "text/plain"
        .col-span-12
          = f.editor :result, mode: "text/plain", read_only: true

app/views/liquidum/sandbox/index.html.slim
= sts.card title: t('.sandboxes'), icon: 'fad fa-toolbox', content_padding: false, menu: liquidum_sandboxes_menu do |card|
  = sts.table 'liquidum/sandboxes', parameters: { search_placeholder: "Search By Context, Template and Description" }